[program:avsb-erp-api-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/deployer/workspace/avsb-erp-api/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deployer
numprocs=2
redirect_stderr=true
stdout_logfile=/home/deployer/workspace/avsb-erp-api/storage/logs/worker.log
stopwaitsecs=600
